apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-workload-identity
  namespace: wif
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: "9092e8e2-3c86-4b9b-af93-ca886100741d" # Setting this to use workload identity
    keyvaultName: ans-aks-csi-driverpoc-kv       # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: secret1
          objectType: secret              # object types: secret, key, or cert
    tenantId: "67d00c3d-4d1e-41cc-93b4-74b100f49098"
  secretObjects:                             
  - secretName: wif-secrets   
    data:
    - key: secret1                          
      objectName: secret1                                        
    type: Opaque